# Generated by Django 5.1.7 on 2025-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='myapp.product'),
        ),
    ]
